# Generated by Django 3.0.3 on 2020-02-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostJobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_type', models.CharField(choices=[('WEBDEVELOPMENT', 'Web Development'), ('WEBDESIGNING', 'Web Designing'), ('ARTCULTURE', 'Art & Culture'), ('READWRITE', 'Read & Writing')], max_length=100)),
                ('offered_salary', models.CharField(choices=[('0-3LAKHS', '0 to 3 Lakhs'), ('3-6LAKHS', '3 to 6 Lakhs'), ('6-12LAKHS', '6 to 12 Lakhs')], max_length=20)),
                ('experience_required', models.CharField(choices=[('0-3YEARS', '0 to 3 Years'), ('3-6YEARS', '3 to 6 Years'), ('6-12YEARS', '6 to 12 Years')], max_length=20)),
            ],
        ),
    ]
