# Generated by Django 3.0.3 on 2020-02-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('company_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('since', models.IntegerField(help_text='Year')),
                ('company_description', models.TextField()),
                ('team_size', models.CharField(max_length=200)),
                ('phone_number', models.CharField(help_text='Enter with area code', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
